apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  namespace: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-container
          image: nginx:latest
          volumeMounts:
            - name: capstone-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: capstone-html
          configMap:
            name: capstone-html
