apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone1
          image: venkateshkesa/capstone:v2
          ports:
            - containerPort: 80
<<<<<<< HEAD
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: capstone-html
              mountPath: /usr/share/nginx/html/
  volumes:
    - name: html
      configMap:
        - name: capstone-html
                       
=======
>>>>>>> f92e825870968583c0294f8b6535f27aba4cd28f
